# render.yaml
services:
  - type: web
    name: product-management-laravel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:GENERATE_THIS_WITH_PHP_ARTISAN_KEY_GENERATE
      - key: APP_URL
        value: https://product-management-laravel.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite

